db:
    container_name: db
    image: mysql:5
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: my-secret-pw
        MYSQL_DATABASE: libreplan
        MYSQL_USER: libreplan
        MYSQL_PASSWORD: secret
    volumes:
        - ./sql:/docker-entrypoint-initdb.d

web:
    container_name: web
    build: .
    dockerfile: Dockerfile
    ports:
        - "8080:8080"
    links:
        - db
